BE - Orders #11
MikeMalyar/PrimumPartusApp pull request #39
Opened 2019-09-23 15:19 UTC by ViktorPelepiak

2019-09-23 15:36 UTC, MikeMalyar requested changes

2019-09-23 15:36 UTC, MikeMalyar commented on src/main/java/com/chnu/controller/OrderController.java
> +        orderService.delete(object);
Do we need this method? It's be easier to use the next one.

2019-09-23 15:36 UTC, MikeMalyar commented on src/main/java/com/chnu/model/Order.java
> +    @Column(name = "order_id")
We need a generation here

2019-09-23 15:36 UTC, MikeMalyar commented on src/main/java/com/chnu/model/Order.java
> +    @OnDelete(action = OnDeleteAction.CASCADE)
May this delete a User while deleting an Order?

2019-09-23 15:36 UTC, MikeMalyar commented on src/main/java/com/chnu/model/Order.java
> +    @OnDelete(action = OnDeleteAction.CASCADE)
May this delete a Company while deleting an Order?

2019-09-23 15:36 UTC, MikeMalyar commented on src/main/java/com/chnu/model/Order.java
> +    @OnDelete(action = OnDeleteAction.CASCADE)
May this delete a Courier while deleting an Order?

2019-09-23 15:36 UTC, MikeMalyar commented on src/main/java/com/chnu/service/impl/OrderService.java
> +
Add @Override annotation on the methods

2019-09-23 15:41 UTC, MikeMalyar commented on src/main/java/com/chnu/model/Order.java
> +    @OnDelete(action = OnDeleteAction.CASCADE)
Think this @OnDelete annotations should be removed from here

2019-09-23 17:14 UTC, MikeMalyar approved these changes

2019-09-24 05:44 UTC, lenyuk1999oo approved these changes

2019-09-24 05:45 UTC, merged