Update/#31
MikeMalyar/PrimumPartusApp pull request #43
Opened 2019-09-27 07:40 UTC by YuraPunchyk

2019-09-27 09:26 UTC, MikeMalyar requested changes

2019-09-27 09:26 UTC, MikeMalyar commented on src/main/java/com/chnu/controller/ProfileController.java
> +    public GenericResponse<Void> delete(@RequestBody Profile object) {
This method may be removed.

2019-09-27 09:26 UTC, MikeMalyar commented on src/main/java/com/chnu/controller/ProfileController.java
> +    public GenericResponse<Void> delete(@RequestBody Profile object) {
We can use the next one.

2019-09-27 09:26 UTC, MikeMalyar commented on src/main/resources/database.properties
> +hibernate.hbm2ddl.auto=create
Please revert this change.

2019-09-27 09:26 UTC, MikeMalyar commented on src/main/java/com/chnu/controller/ProfileController.java
> +                GenericResponse.error("This profile already exist.");
Move this message into message properties and get it using properties utility.

2019-09-27 09:26 UTC, MikeMalyar commented on src/main/java/com/chnu/controller/ProfileController.java
> +                GenericResponse.error("Profile not found with id " + pk);
Move this message into message properties and get it using properties utility.

2019-09-27 09:26 UTC, MikeMalyar commented on src/main/java/com/chnu/controller/ProfileController.java
> +        return GenericResponse.error("Profile is null.");
Move this message into message properties and get it using properties utility.

2019-09-27 09:26 UTC, MikeMalyar commented on src/main/java/com/chnu/controller/ProfileController.java
> +        return GenericResponse.empty();
Maybe we need a message about successful object deleting ?

2019-10-08 06:18 UTC, MikeMalyar approved these changes

2019-10-08 06:32 UTC, ViktorPelepiak approved these changes

2019-10-08 06:32 UTC, lenyuk1999oo approved these changes

2019-10-08 06:32 UTC, merged